{% set name = "pysqlite3" %}
{% set version = "0.3.0" %}

{% set amalgamation_version = "3290000" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
    sha256: 74bfe92c4febce11ee05f741d9b6406e1919440807a315c65f2e0b489fe9eb75
  - url: https://www.sqlite.org/2019/sqlite-amalgamation-{{ amalgamation_version }}.zip
    sha1: a0eba79e5d1627946aead47e100a8a6f9f6fafff

build:
  number: 0
  skip: True  # [py2k]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - pysqlite3
    - pysqlite3.dbapi2

about:
  home: https://github.com/coleifer/pysqlite3
  license: zlib
  license_file: LICENSE
  license_family: other
  summary: 'SQLite3 DB-API 2.0 driver from Python 3, packaged separately, with improvements'
  description: |
    This library takes the SQLite module from Python 3 and packages it as a separately-installable module.
    This may be useful for creating SQLite modules capable of working with other versions of SQLite (via the amalgamation option).
  dev_url: https://github.com/coleifer/pysqlite3

extra:
  recipe-maintainers:
    - jakakokosar
